export dfi_config=0

cd $SPECPATH/447.dealII/src/
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o auto_derivative_function.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       auto_derivative_function.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o block_sparse_matrix.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       block_sparse_matrix.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o block_sparse_matrix_ez.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       block_sparse_matrix_ez.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o block_sparsity_pattern.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       block_sparsity_pattern.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o block_vector.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       block_vector.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o compressed_sparsity_pattern.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       compressed_sparsity_pattern.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o data_out.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       data_out.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o data_out_base.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       data_out_base.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o data_out_faces.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       data_out_faces.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o data_out_rotation.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       data_out_rotation.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o data_out_stack.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       data_out_stack.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o derivative_approximation.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       derivative_approximation.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o dof_accessor.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       dof_accessor.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o dof_constraints.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       dof_constraints.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o dof_handler.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       dof_handler.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o dof_levels.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       dof_levels.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o dof_renumbering.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       dof_renumbering.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o dof_tools.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       dof_tools.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o error_estimator.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       error_estimator.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o exceptions.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       exceptions.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_data.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_data.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgp.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgp.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgp_1d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgp_1d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgp_2d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgp_2d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgp_3d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgp_3d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgp_nonparametric.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgp_nonparametric.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgq.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgq.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgq_1d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgq_1d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgq_2d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgq_2d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgq_3d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgq_3d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_nedelec.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_nedelec.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_nedelec_1d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_nedelec_1d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_nedelec_2d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_nedelec_2d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_nedelec_3d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_nedelec_3d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_q.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_q.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_q_1d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_q_1d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_q_2d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_q_2d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_q_3d.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_q_3d.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_q_hierarchical.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_q_hierarchical.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_raviart_thomas.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_raviart_thomas.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_system.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_system.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_tools.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_tools.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_values.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_values.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o filtered_matrix.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       filtered_matrix.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o full_matrix.double.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       full_matrix.double.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o full_matrix.float.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       full_matrix.float.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o function.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       function.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o function_derivative.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       function_derivative.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o function_lib.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       function_lib.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o function_lib_cutoff.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       function_lib_cutoff.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o function_time.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       function_time.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o geometry_info.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       geometry_info.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o grid_generator.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       grid_generator.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o grid_in.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       grid_in.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o grid_out.all_dimensions.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       grid_out.all_dimensions.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o grid_out.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       grid_out.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o grid_refinement.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       grid_refinement.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o grid_reordering.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       grid_reordering.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o histogram.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       histogram.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o intergrid_map.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       intergrid_map.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o job_identifier.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       job_identifier.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o log.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       log.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mapping.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mapping.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mapping_c1.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mapping_c1.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mapping_cartesian.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mapping_cartesian.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mapping_q.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mapping_q.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mapping_q1.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mapping_q1.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mapping_q1_eulerian.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mapping_q1_eulerian.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o matrices.all_dimensions.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       matrices.all_dimensions.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o matrices.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       matrices.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o matrix_lib.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       matrix_lib.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o matrix_out.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       matrix_out.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o memory_consumption.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       memory_consumption.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_base.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_base.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_dof_accessor.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_dof_accessor.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_dof_handler.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_dof_handler.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_dof_tools.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_dof_tools.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_smoother.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_smoother.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_transfer_block.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_transfer_block.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_transfer_prebuilt.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_transfer_prebuilt.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o mg_transfer_block.all_dimensions.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       mg_transfer_block.all_dimensions.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o multigrid.all_dimensions.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       multigrid.all_dimensions.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o multithread_info.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       multithread_info.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o parameter_handler.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       parameter_handler.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o persistent_tria.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       persistent_tria.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o polynomial.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       polynomial.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o polynomial_space.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       polynomial_space.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o programid.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       programid.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o quadrature.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       quadrature.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o quadrature_lib.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       quadrature_lib.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o solution_transfer.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       solution_transfer.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o solver_control.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       solver_control.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o sparse_matrix.double.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       sparse_matrix.double.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o sparse_matrix.float.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       sparse_matrix.float.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o sparse_matrix_ez.double.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       sparse_matrix_ez.double.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o sparse_matrix_ez.float.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       sparse_matrix_ez.float.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o sparsity_pattern.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       sparsity_pattern.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o step-14.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       step-14.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o subscriptor.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       subscriptor.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o swappable_vector.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       swappable_vector.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o tensor.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       tensor.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o tensor_product_polynomials.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       tensor_product_polynomials.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o tria.all_dimensions.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       tria.all_dimensions.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o tria.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       tria.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o tria_accessor.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       tria_accessor.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o tria_boundary.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       tria_boundary.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o tria_boundary_lib.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       tria_boundary_lib.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o vector.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       vector.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o vector.long_double.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       vector.long_double.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o vectors.all_dimensions.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       vectors.all_dimensions.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_dgp_monomial.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_dgp_monomial.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o fe_poly.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       fe_poly.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o polynomials_bdm.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       polynomials_bdm.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o polynomials_p.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       polynomials_p.cc
$LLVMPATH/bin/clang++ -emit-llvm -c -std=c++98 -o vectors.bc -DSPEC_CPU -DNDEBUG  -Iinclude -DBOOST_DISABLE_THREADS -Ddeal_II_dimension=3   -O3    -DSPEC_CPU_LP64       vectors.cc
cp *.bc $WORKPATH
rm *.bc

cd $WORKPATH
$LLVMPATH/bin/llvm-link    auto_derivative_function.bc block_sparse_matrix.bc block_sparse_matrix_ez.bc block_sparsity_pattern.bc block_vector.bc compressed_sparsity_pattern.bc data_out.bc data_out_base.bc data_out_faces.bc data_out_rotation.bc data_out_stack.bc derivative_approximation.bc dof_accessor.bc dof_constraints.bc dof_handler.bc dof_levels.bc dof_renumbering.bc dof_tools.bc error_estimator.bc exceptions.bc fe.bc fe_data.bc fe_dgp.bc fe_dgp_1d.bc fe_dgp_2d.bc fe_dgp_3d.bc fe_dgp_nonparametric.bc fe_dgq.bc fe_dgq_1d.bc fe_dgq_2d.bc fe_dgq_3d.bc fe_nedelec.bc fe_nedelec_1d.bc fe_nedelec_2d.bc fe_nedelec_3d.bc fe_q.bc fe_q_1d.bc fe_q_2d.bc fe_q_3d.bc fe_q_hierarchical.bc fe_raviart_thomas.bc fe_system.bc fe_tools.bc fe_values.bc filtered_matrix.bc full_matrix.double.bc full_matrix.float.bc function.bc function_derivative.bc function_lib.bc function_lib_cutoff.bc function_time.bc geometry_info.bc grid_generator.bc grid_in.bc grid_out.all_dimensions.bc grid_out.bc grid_refinement.bc grid_reordering.bc histogram.bc intergrid_map.bc job_identifier.bc log.bc mapping.bc mapping_c1.bc mapping_cartesian.bc mapping_q.bc mapping_q1.bc mapping_q1_eulerian.bc matrices.all_dimensions.bc matrices.bc matrix_lib.bc matrix_out.bc memory_consumption.bc mg_base.bc mg_dof_accessor.bc mg_dof_handler.bc mg_dof_tools.bc mg_smoother.bc mg_transfer_block.bc mg_transfer_prebuilt.bc mg_transfer_block.all_dimensions.bc multigrid.all_dimensions.bc multithread_info.bc parameter_handler.bc persistent_tria.bc polynomial.bc polynomial_space.bc programid.bc quadrature.bc quadrature_lib.bc solution_transfer.bc solver_control.bc sparse_matrix.double.bc sparse_matrix.float.bc sparse_matrix_ez.double.bc sparse_matrix_ez.float.bc sparsity_pattern.bc step-14.bc subscriptor.bc swappable_vector.bc tensor.bc tensor_product_polynomials.bc tria.all_dimensions.bc tria.bc tria_accessor.bc tria_boundary.bc tria_boundary_lib.bc vector.bc vector.long_double.bc vectors.all_dimensions.bc fe_dgp_monomial.bc fe_poly.bc polynomials_bdm.bc polynomials_p.bc vectors.bc   -o dealII.bc

